package com.example.jason.examination.constants;

/**
 * Created by Chuanlong on 2016/12/9.
 */

public class ConstKey {

    public final static int KEY_LOGIN_PLATFORM_GOOGLE = 5;
    public final static int KEY_LOGIN_PLATFORM_FACEBOOK = 9;


    public final static String INTENT_KEY_USER_INFO_ID = "INTENT_KEY_USER_INFO_ID";

    public final static String INTENT_KEY_ATTENTION_OTHERS_ACTIVITY = "INTENT_KEY_ATTENTION_OTHERS_ACTIVITY";

    public final static String INTENT_KEY_ATTENTION_OTHERS_ACTIVITY_STATE = "INTENT_KEY_ATTENTION_OTHERS_ACTIVITY_STATE";

    public final static String INTENT_KEY_WORKS_ITEM_POSITION = "INTENT_KEY_WORKS_ITEM_POSITION";

    public final static String INTENT_KEY_WORKS_LIST = "INTENT_KEY_WORKS_LIST";

    public final static String INTENT_KEY_MEDIA_DETAIL_OBJ = "INTENT_KEY_MEDIA_DETAIL_OBJ";

    public final static String INTENT_KEY_NEW_WORKS_INFO_FRAGMENT = "INTENT_KEY_NEW_WORKS_INFO_FRAGMENT";

    public final static String INTENT_KEY_MEDIA_DETAIL_TO_WORKS_INFO_ACTIVITY = "INTENT_KEY_MEDIA_DETAIL_TO_WORKS_INFO_ACTIVITY";

    public final static String INTENT_KEY_MEDIA_DETAIL_NEW_WORKS_FRAGMENT_KEY = "INTENT_KEY_MEDIA_DETAIL_NEW_WORKS_FRAGMENT_KEY";

    public final static String INTENT_KEY_MEDIA_DETAIL_ID = "INTENT_KEY_MEDIA_DETAIL_ID";

    public final static String INTENT_KEY_MEDIA_DETAIL_COMMENT_COUNT = "INTENT_KEY_MEDIA_DETAIL_COMMENT_COUNT";

    public final static String INTENT_KEY_MEDIA_DETAIL_POSITION = "INTENT_KEY_MEDIA_DETAIL_POSITION";

    public final static String INTENT_KEY_MESSAGE_USER_LIST = "INTENT_KEY_MESSAGE_USER_LIST";

    public final static String INTENT_KEY_VIDEO_INFO = "INTENT_KEY_VIDEO_INFO";

    public final static String INTENT_KEY_CLOUD_MUSIC_PATH = "INTENT_KEY_CLOUD_MUSIC_PATH";

    public final static String INTENT_KEY_CLOUD_MUSIC_LRC_PATH = "INTENT_KEY_CLOUD_MUSIC_LRC_PATH";

    public final static String INTENT_KEY_CLOUD_MUSIC_ICON_PATH = "INTENT_KEY_CLOUD_MUSIC_ICON_PATH";

    public final static String INTENT_KEY_CLOUD_MUSIC_NOT_CHOOSE = "INTENT_KEY_CLOUD_MUSIC_NOT_CHOOSE";

    public final static String INTENT_KEY_TO_LOCAL_VIDEO_PREVIEW_ACTIVITY_TOPIC_TITLE = "INTENT_KEY_TO_LOCAL_VIDEO_PREVIEW_ACTIVITY_TOPIC_TITLE";

    public final static String INTENT_KEY_TO_LOCAL_VIDEO_PREVIEW_ACTIVITY_TOPIC_ID = "INTENT_KEY_TO_LOCAL_VIDEO_PREVIEW_ACTIVITY_TOPIC_ID";

    public final static String INTENT_KEY_TO_TOPIC_INFO_ACTIVITY_TOPIC_ID = "INTENT_KEY_TO_TOPIC_INFO_ACTIVITY_TOPIC_ID";

    public final static String INTENT_KEY_TO_TOPIC_MORE_USER_ACTIVITY = "INTENT_KEY_TO_TOPIC_MORE_USER_ACTIVITY";

    public final static String INTENT_KEY_TO_TOPIC_INFO_ACTIVITY_TOPIC_TITLE = "INTENT_KEY_TO_TOPIC_INFO_ACTIVITY_TOPIC_TITLE";

    public final static String INTENT_KEY_TO_TOPIC_INFO_ACTIVITY_TOPIC_DESCRIPTION = "INTENT_KEY_TO_TOPIC_INFO_ACTIVITY_TOPIC_DESCRIPTION";

    public final static String INTENT_KEY_TO_WEB_VIEW_ACTIVITY_TITLE = "INTENT_KEY_TO_WEB_VIEW_ACTIVITY_TITLE";

    public final static String INTENT_KEY_TO_WEB_VIEW_ACTIVITY_URL = "INTENT_KEY_TO_WEB_VIEW_ACTIVITY_URL";

    public final static String KEY_NEW_COMMENT_FRAGMENT = "KEY_NEW_COMMENT_FRAGMENT";

    public final static String KEY_NEW_FANS_FRAGMENT = "KEY_NEW_FANS_FRAGMENT";

    public final static String KEY_NEW_FANS_FRAGMENT_USER_ID = "KEY_NEW_FANS_FRAGMENT_USER_ID";

    public final static String KEY_NEW_VIDEO_MANAGE_FRAGMENT = "KEY_NEW_VIDEO_MANAGE_FRAGMENT";

    public final static String KEY_VIDEO_MOMENTS_FRAGMENT_CATEGORY = "KEY_VIDEO_MOMENTS_FRAGMENT_CATEGORY";

    public final static String KEY_NEW_WORKS_FRAGMENT = "KEY_NEW_WORKS_FRAGMENT";

    public final static String KEY_NEW_WORKS_FRAGMENT_USER_ID = "KEY_NEW_WORKS_FRAGMENT_USER_ID";


    public final static String KEY_NEW_NOT_LOGGED_IN_NEWS_ACTIVITY_FRAGMENT = "KEY_NEW_NOT_LOGGED_IN_NEWS_ACTIVITY_FRAGMENT";

    public final static String KEY_NEW_MEDIA_UPLOAD_EVENT_UPLOAD_VIDEO_SUCCESS = "KEY_NEW_MEDIA_UPLOAD_EVENT_UPLOAD_VIDEO_SUCCESS";

    public final static String KEY_NEW_MEDIA_UPLOAD_EVENT_UPLOAD_VIDEO_FAILED = "KEY_NEW_MEDIA_UPLOAD_EVENT_UPLOAD_VIDEO_FAILED";

    public final static String KEY_REFRESH_VIDEO_LIST = "KEY_REFRESH_VIDEO_LIST";

    public final static String KEY_MEDIA_MANAGE_SELECT_ACTIVITY_FINISH = "KEY_MEDIA_MANAGE_SELECT_ACTIVITY_FINISH";

    public final static String KEY_WIFI_REMIND_Shared_Preference = "KEY_WIFI_REMIND_Shared_Preference";

    public final static String KEY_WIFI_REMIND_Shared_Preference_NAME = "KEY_WIFI_REMIND_Shared_Preference_NAME";

    public final static String KEY_WIFI_REMIND_Shared_Preference_REMIND_EVERY_TIME = "KEY_WIFI_REMIND_Shared_Preference_REMIND_EVERY_TIME";

    public final static String KEY_YUV_DATA_WIDTH = "KEY_YUV_DATA_WIDTH";

    public final static String KEY_YUV_DATA_HEIGHT = "KEY_YUV_DATA_HEIGHT";

    public final static String KEY_YUV_DATA_PATH = "KEY_YUV_DATA_PATH";

    public final static String KEY_COVER_PAGE_BITMAP_PATH = "KEY_COVER_PAGE_BITMAP_PATH";

    public final static String KEY_YUV_DATA_FRAME_RATE = "KEY_YUV_DATA_FRAME_RATE";


    public final static String KEY_LAST_LOGIN_TIME = "KEY_LAST_LOGIN_TIME";


    public final static String KEY_CLEAR_CACHE_SUCCESS = "KEY_CLEAR_CACHE_SUCCESS";

    public final static String KEY_NEW_MEDIA_UPLOAD_EVENT_COMMENT_ACTIVITY_BACK = "KEY_NEW_MEDIA_UPLOAD_EVENT_COMMENT_ACTIVITY_BACK";

    public final static int REQUEST_CODE_FIREBASE_MESSAGING = 10001;

    public final static int REQUEST_CODE_GOOGLE_LOGIN = 10002;

    public final static int REQUEST_CODE_CHOOSE_MUSIC = 20001;

    public final static int REQUEST_COVER_PAGE_EDIT = 20002;

    public final static float TOPIC_BACKGROUND_ALPHA = (float) 0.5;

    public final static float BACKGROUND_ALPHA = (float) 1;


}
